COMPILE = g++ -Wall -Wshadow -O3 -g -o reconstruct2contourtiler
LINK = g++

reconstruct2contourtiler: classes.cc functions.cc reconstruct2contourtiler.cc  
	$(COMPILE) reconstruct2contourtiler.cc

clean:
	-rm *.o
