Object Class Reference
#include <object.h>
Public Member Functions
Object (char const *const str, const int &sec)
Object & operator= (Object const &)
Object (Object const &)
int getNumRawPoints (void) const
int getRanges (std::vector< int > &ranges) const
void printRawPoints (void) const
void purgeBadContours (void)
void removeDuplicates (void)
void processContour (Histogram &h, Histogram &si, Histogram &si_before)
void addContour (Contour mycontour)
void computeHistogram (Histogram &h, Histogram &si)
void writeOutputContours (const int &num_parts, const std::vector< int > &ranges)
void clearPtsFiles (const int &num_parts, const std::vector< int > &ranges) const
int getNumContours (void) const
c_c_l_iterator firstContour (void) const
c_c_l_iterator onePastLastContour (void) const
c_l_iterator getLastContour (void)
void setMinSection (int i)
void setMaxSection (int i)
int getMaxSection (void) const
int getMinSection (void) const
char const * getName (void) const
Constructor & Destructor Documentation
Object::Object (char const *const str, const int & sec)
Object::Object (Object const & rhs)
Member Function Documentation
Object & Object::operator= (Object const & rhs)
References name.
int Object::getNumRawPoints (void) const
Get cumulative number of points in all contours in this object.
int Object::getRanges (std::vector< int > & ranges) const
void Object::printRawPoints (void) const
Print raw contour points to file
References Controls::instance().
void Object::purgeBadContours (void)
Erase contours with fewer points than user-specified threshold.
References Controls::getPtPerContourThreshold(), and Controls::instance().
void Object::removeDuplicates (void)
Remove duplicate points in each contour of object.
void Object::processContour (Histogram & h, Histogram & si, Histogram & si_before)
Fit splines to contour points in each contour in this object.
Parameters:
$\leftarrow$ h Instance of Histogram class for sample point deviations.
$\leftarrow$ si Instance of Histogram class for sample intervals after simulated annealing.
$\leftarrow$ si_before Instance of Histogram class for sample intervals before simulated annealing.
References Histogram::getN(), Controls::getPrintDetailedInfo(), Controls::getPtPerContourThreshold(), Controls::instance(), Histogram::scan(), and Histogram::update().
void Object::addContour (Contour mycontour)
Add new contour to object.
Parameters:
$\leftarrow$ mycontour New contour.
void Object::computeHistogram (Histogram & h, Histogram & si)
void Object::writeOutputContours (const int & num_parts, const std::vector< int > & ranges)
Write output contour points to file.
Parameters:
$\leftarrow$ num_parts Number of separate parts of object.
$\leftarrow$ ranges Section numbers of object parts.
References Controls::getCappingFlag(), Controls::getMultiPartSuffix(), Controls::getPrintDetailedInfo(), and Controls::instance().
void Object::clearPtsFiles (const int & num_parts, const std::vector< int > & ranges) const [inline]
Initialize all output pts files to empty.
References Controls::getMultiPartSuffix(), Controls::getOutputDir(), and Controls::instance().
int Object::getNumContours (void) const [inline]
c_c_l_iterator Object::firstContour (void) const [inline]
c_c_l_iterator Object::onePastLastContour (void) const [inline]
c_l_iterator Object::getLastContour (void) [inline]
void Object::setMinSection (int i) [inline]
void Object::setMaxSection (int i) [inline]
int Object::getMaxSection (void) const [inline]
int Object::getMinSection (void) const [inline]
char const* Object::getName (void) const [inline]
The documentation for this class was generated from the following files:
object.h
object.cc