Container Class Reference
#include <container.h>
Public Member Functions
void processContour (Histogram &h, Histogram &si, Histogram &si_before)
void clearOutputScripts (void)
void getContours (void)
void writeOutputContours (void)
Container (void)
int getNumFiles (void) const
int getNumObjects (void) const
int getNumContours (void) const
int getNumRawPoints (void) const
c_l_iterator getLastContourFromObject (char const *const object_name)
o_iterator firstObjectNonConst (void)
o_iterator onePastLastObjectNonConst (void)
c_o_iterator firstObject (void) const
c_o_iterator onePastLastObject (void) const
void purgeBadContours (void)
void removeDuplicates (void)
void computeHistogram (Histogram &h, Histogram &si)
void printRawPoints (void) const
Constructor & Destructor Documentation
Container::Container (void) [inline]
Create new instance of Container class.
References Controls::instance().
Member Function Documentation
void Container::processContour (Histogram & h, Histogram & si, Histogram & si_before)
Process contours in each object.
Parameters:
$\leftarrow$ h Instance of Histogram class for sample point deviations.
$\leftarrow$ si Instance of Histogram class for sample intervals after simulated annealing.
$\leftarrow$ si_before Instance of Histogram class for sample intervals before simulated annealing.
Referenced by main().
void Container::clearOutputScripts (void)
Initialize output script to empty.
References Controls::getOutputDir(), Controls::getOutputScript(), and Controls::instance().
Referenced by main().
void Container::getContours (void)
Load contour data from file.
References Controls::getInputDir(), getLastContourFromObject(), Controls::getMaxSection(), Controls::getMinSection(), Controls::getPrefix(), and Controls::instance().
Referenced by main().
void Container::writeOutputContours (void)
Write output contour points to file.
Referenced by main().
int Container::getNumFiles (void) const [inline]
Get number of input files read.
Returns: Number of input files read.
Referenced by main().
int Container::getNumObjects (void) const [inline]
Get number of different input objects found.
Returns: Number of objects.
Referenced by main().
int Container::getNumContours (void) const [inline]
Get cumulative number of contours of all objects.
Referenced by main().
int Container::getNumRawPoints (void) const [inline]
Get cumulative number of points in all contours of all objects.
Referenced by main().
c_l_iterator Container::getLastContourFromObject (char const *const object_name) [inline]
Get iterator to last contour of object with specified name.
Parameters:
$\leftarrow$ object_name Object of interest.
Returns: Iterator to last contour in object.
Referenced by getContours().
o_iterator Container::firstObjectNonConst (void) [inline]
Get iterator to first object.
o_iterator Container::onePastLastObjectNonConst (void) [inline]
Get iterator to one past last object.
c_o_iterator Container::firstObject (void) const [inline]
Get iterator to first object.
c_o_iterator Container::onePastLastObject (void) const [inline]
Get iterator to one past last object.
void Container::purgeBadContours (void) [inline]
Remove contours with too few points in each object in container.
void Container::removeDuplicates (void) [inline]
Remove duplicate points in each object in container.
Referenced by main().
void Container::computeHistogram (Histogram & h, Histogram & si) [inline]
For each object in container compute histogram of deviaton distance between spline samples and linearly interpolated input contour points.
Parameters:
$\leftarrow$ h Instance of Histogram class for sample point deviations.
$\leftarrow$ si Instance of Histogram class for sample intervals after simulated annealing.
void Container::printRawPoints (void) const [inline]
For each object in container write input contour points to file.
Referenced by main().
The documentation for this class was generated from the following files:
container.h
container.cc