Controls Class Reference
#include <controls.h>
Public Member Functions
void parseCommandLine (int, char **)
std::string getUsageMessage (void)
int getNumReserve () const throw ()
int getCappingFlag () const throw ()
int getMinSection () const throw ()
int getMaxSection () const throw ()
int getPrintDetailedInfo () const throw ()
int getReturnRawContourPoints () const throw ()
int getReturnInterpolatedRawPoints () const throw ()
int getPtPerContourThreshold () const throw ()
int getNumMovesPerIteration () const throw ()
int getMaxNumMoveAttempts () const throw ()
int getIntegrationStep () const throw ()
int getMaxDeviationAdjustments () const throw ()
int getCurvatureEnergyExponent () const throw ()
int getProximityEnergyExponent () const throw ()
double getAdditionalPointsFactor () const throw ()
double getIntegrationStepFactor () const throw ()
double getHighTemp () const throw ()
double getTempScale () const throw ()
double getBoltzman () const throw ()
double getCurvatureEnergyGain () const throw ()
double getProximityEnergyGain () const throw ()
double getMeanAmplitudeNoise () const throw ()
double getMaxRadiusOfCurvature () const throw ()
double getSectionThickness () const throw ()
double getOutputScaleFactor () const throw ()
double getDeviationThreshold () const throw ()
double getEpsilon () const throw ()
double getMaxSampleInterval () const throw ()
double getMinSampleInterval () const throw ()
char const * getInputDir () const throw ()
char const * getOutputDir () const throw ()
char const * getPrefix () const throw ()
char const * getOutputScript () const throw ()
char const * getMultiPartSuffix () const throw ()
void validate (void)
bool contourIsIgnored (char const *const name) const
std::string d2str (double const &num) const
std::string i2str (int const &num) const
std::string processDir (char *ptr) const
Static Public Member Functions
static Controls & instance (void)
Member Function Documentation
Controls & Controls::instance (void) [static]
Referenced by Contour::clearArcLengthsLogFiles(), Contour::clearControlLogFiles(), Container::clearOutputScripts(), Object::clearPtsFiles(), Contour::clearRadiusCurvatureLogFiles(), Contour::clearSampleLogFiles(), Contour::clearSParamLogFiles(), Contour::clearUniformSampleLogFiles(), Container::Container(), Sim_Anneal::debug(), Sim_Anneal::decreaseTemp(), Parameter::deviationsLarge(), distinguishable(), Contour::fewButKeep(), Contour::fewOmit(), Container::getContours(), Sim_Anneal::getNormalRandom(), Parameter::getRawPointsToDuplicate(), Contour::initializeControlPointVector(), Sim_Anneal::isFrozen(), main(), Sim_Anneal::moreMoves(), Contour::printPtsFiles(), Object::printRawPoints(), Contour::printRawPtsFiles(), Sim_Anneal::printScript(), Contour::printScripts(), Contour::printSimpleScripts(), Object::processContour(), Contour::processContour(), Object::purgeBadContours(), Contour::setSamplesToRaw(), Contour::writeFilesAfter(), and Object::writeOutputContours().
void Controls::parseCommandLine (int argc, char ** argv)
Parse command line.
Parameters:
$\leftarrow$ argc Argc.
$\leftarrow$ argv Argv.
References getUsageMessage(), processDir(), and validate().
Referenced by main().
std::string Controls::getUsageMessage (void)
Create usage message.
Returns: usage message.
References d2str(), and i2str().
Referenced by parseCommandLine().
int Controls::getNumReserve () const throw () [inline]
int Controls::getCappingFlag () const throw () [inline]
Referenced by Object::writeOutputContours().
int Controls::getMinSection () const throw () [inline]
Referenced by Container::getContours().
int Controls::getMaxSection () const throw () [inline]
Referenced by Container::getContours().
int Controls::getPrintDetailedInfo () const throw () [inline]
Referenced by main(), Object::processContour(), Contour::processContour(), and Object::writeOutputContours().
int Controls::getReturnRawContourPoints () const throw () [inline]
int Controls::getReturnInterpolatedRawPoints () const throw () [inline]
Referenced by Contour::initializeControlPointVector().
int Controls::getPtPerContourThreshold () const throw () [inline]
Referenced by Contour::fewButKeep(), Contour::fewOmit(), Object::processContour(), and Object::purgeBadContours().
int Controls::getNumMovesPerIteration () const throw () [inline]
Referenced by Sim_Anneal::debug(), and Sim_Anneal::moreMoves().
int Controls::getMaxNumMoveAttempts () const throw () [inline]
Referenced by Sim_Anneal::debug(), and Sim_Anneal::moreMoves().
int Controls::getIntegrationStep () const throw () [inline]
int Controls::getMaxDeviationAdjustments () const throw () [inline]
int Controls::getCurvatureEnergyExponent () const throw () [inline]
int Controls::getProximityEnergyExponent () const throw () [inline]
double Controls::getAdditionalPointsFactor () const throw () [inline]
double Controls::getIntegrationStepFactor () const throw () [inline]
double Controls::getHighTemp () const throw () [inline]
double Controls::getTempScale () const throw () [inline]
Referenced by Sim_Anneal::decreaseTemp().
double Controls::getBoltzman () const throw () [inline]
Referenced by Sim_Anneal::decreaseTemp().
double Controls::getCurvatureEnergyGain () const throw () [inline]
double Controls::getProximityEnergyGain () const throw () [inline]
double Controls::getMeanAmplitudeNoise () const throw () [inline]
Referenced by Sim_Anneal::getNormalRandom().
double Controls::getMaxRadiusOfCurvature () const throw () [inline]
double Controls::getSectionThickness () const throw () [inline]
Referenced by Contour::printPtsFiles(), and Contour::printRawPtsFiles().
double Controls::getOutputScaleFactor () const throw () [inline]
Referenced by Contour::printPtsFiles(), and Contour::printRawPtsFiles().
double Controls::getDeviationThreshold () const throw () [inline]
Referenced by Parameter::deviationsLarge(), and Parameter::getRawPointsToDuplicate().
double Controls::getEpsilon () const throw () [inline]
double Controls::getMaxSampleInterval () const throw () [inline]
double Controls::getMinSampleInterval () const throw () [inline]
char const* Controls::getInputDir () const throw () [inline]
Referenced by Container::getContours().
char const* Controls::getOutputDir () const throw () [inline]
Referenced by Container::clearOutputScripts(), Object::clearPtsFiles(), Contour::printPtsFiles(), Contour::printRawPtsFiles(), Sim_Anneal::printScript(), Contour::printScripts(), Contour::printSimpleScripts(), Contour::processContour(), and Contour::writeFilesAfter().
char const* Controls::getPrefix () const throw () [inline]
Referenced by Container::getContours().
char const* Controls::getOutputScript () const throw () [inline]
Referenced by Container::clearOutputScripts().
char const* Controls::getMultiPartSuffix () const throw () [inline]
Referenced by Object::clearPtsFiles(), and Object::writeOutputContours().
void Controls::validate (void) [inline]
Validate the values for control parameters.
Referenced by parseCommandLine().
bool Controls::contourIsIgnored (char const *const name) const [inline]
Determine if contour is to be ignored.
Parameters:
$\leftarrow$ name Name of contour.
Returns: True if contour is to be ignored; false otherwise.
std::string Controls::d2str (double const & num) const [inline]
Create string from floating point number.
Parameters:
$\leftarrow$ num Number of interest.
Returns: String containing input number.
Referenced by getUsageMessage().
std::string Controls::i2str (int const & num) const [inline]
Create string from integer number.
Parameters:
$\leftarrow$ num Number of interest.
Returns: String containing input number.
Referenced by getUsageMessage().
std::string Controls::processDir (char * ptr) const [inline]
Ensure pathname ends with exactly one '/'.
Parameters:
$\leftarrow$ ptr Arbitrary pathname.
Returns: Input pathname with '/' added if absent.
Referenced by parseCommandLine().
The documentation for this class was generated from the following files:
controls.h
controls.cc