reconstruct2contourtiler.h File Reference
#include <vector>
#include `container.h`
#include `controls.h`
Defines
#define RECONSTRUCT2CONTOURTILER_H 1
Functions
bool distinguishable (double a, double b, double epsilon)
bool distinguishable (double a, double b)
Define Documentation
#define RECONSTRUCT2CONTOURTILER_H 1
Function Documentation
bool distinguishable (double a, double b)
Determine if two floating-point precision numbers are equivalent in value within MY_DOUBLE_EPSILON.
Parameters:
$\leftarrow$ a First number.
$\leftarrow$ b Second number.
Returns: 1 if Inputs are different; 0 otherwise.
References distinguishable(), and Controls::instance().
bool distinguishable (double a, double b, double epsilon)
Determine if two floating-point precision numbers are equivalent in value within epsilon.
Parameters:
$\leftarrow$ a First number.
$\leftarrow$ b Second number.
$\leftarrow$ epsilon The difference between the two input values must be greater than the fraction of the largest input value defined by epsilon.
Returns: 1 if Inputs are different; 0 otherwise.
Referenced by distinguishable().