echo "examples/bad1.mesh" >> output.log
./meshalyzer examples/bad1.mesh >> output.log
echo "examples/bad_mesh.mesh" >> output.log
./meshalyzer examples/bad_mesh.mesh >> output.log
echo "examples/bad_mesh_too.mesh" >> output.log
./meshalyzer examples/bad_mesh_too.mesh >> output.log
echo "examples/example0.mesh" >> output.log
./meshalyzer examples/example0.mesh >> output.log
echo "examples/example1.mesh" >> output.log
./meshalyzer examples/example1.mesh >> output.log
echo "examples/example2.mesh" >> output.log
./meshalyzer examples/example2.mesh >> output.log
echo "examples/example3.mesh" >> output.log
./meshalyzer examples/example3.mesh >> output.log
