Histogram Class Reference
#include <histogram.h>
Public Member Functions
void scan (const vec_d &my_path_intervals)
~Histogram (void)
Histogram (void)
void printHistogram (void)
void printStats (void) const
void createHistogram (void)
void update (double const &)
void printStatistics (std::string str)
double mean (void) const
double variance (void) const
double getMax (void) const
double getSum (void) const
int getN (void) const
void incrementCount (int i)
Constructor & Destructor Documentation
Histogram::~Histogram (void)
Histogram::Histogram (void)
Member Function Documentation
void Histogram::scan (const vec_d & my_path_intervals)
Record statistics of straight-line distances between sample points.
Parameters:
$\leftarrow$ my_path_intervals Inter-sample distances.
References update().
Referenced by Object::processContour().
void Histogram::printHistogram (void)
Print histogram.
Referenced by printStatistics().
void Histogram::printStats (void) const
Print summary statistics.
References mean(), and variance().
Referenced by printStatistics().
void Histogram::createHistogram (void)
Calculate bin partitions and then bin data.
References mean(), and variance().
Referenced by printStatistics().
void Histogram::update (double const & d)
Update statistics of data.
Parameters:
$\leftarrow$ d New data point.
Referenced by Object::processContour(), scan(), Contour::updateDeviations(), and Contour::updateSampleIntervals().
void Histogram::printStatistics (std::string str)
References createHistogram(), printHistogram(), and printStats().
Referenced by main().
double Histogram::mean (void) const
Compute mean value.
Returns: Mean.
Referenced by createHistogram(), and printStats().
double Histogram::variance (void) const
Compute variance value.
Returns: Variance.
Referenced by createHistogram(), and printStats().
double Histogram::getMax (void) const [inline]
double Histogram::getSum (void) const [inline]
int Histogram::getN (void) const [inline]
Referenced by Object::processContour().
void Histogram::incrementCount (int i) [inline]
The documentation for this class was generated from the following files:
histogram.h
histogram.cc