Contour Class Reference
#include <contour.h>
Public Member Functions
Contour (char *const str, int sec)
Contour & operator= (Contour const &)
Contour (Contour const &)
int processContour (vec_d &my_path_intervals)
bool isDegenerate (void) const
void computeDeviationHistogram (Histogram &h) const
void computeIntervalHistogram (Histogram &h) const
void updateDeviations (Histogram &h) const
void calcSampleIntervals (vec_d &my_path_intervals)
void updateSampleIntervals (Histogram &h)
void setSamplesToRaw (void)
void removeDuplicates (void)
void writeFilesAfter (void) const
void printPtsFiles (char const *myname) const
void printRawPtsFiles (char const *myname) const
void printScripts (void) const
void printSimpleScripts (void) const
void printRawPoints (char const *const filename) const
void printSplineSamplesHere (char const *const filename, const int &num_splines, double path_parameter_value) const
void duplicateControlPoints (list_i &control_points) const
void printIdentity (void)
void addRawPoint (Point p)
int getNumSamplePoints (void) const
int getNumRawPoints (void) const
bool pointsAreIdentical (Point const &lhs, Point const &rhs) const
char const * getName (void) const
c_d_iterator firstDeviation (void)
c_d_iterator onePastLastDeviation (void)
c_p_iterator getFirstRawPoint (void)
c_p_iterator getOnePastLastRawPoint (void)
int getSection (void) const
void initializeControlPointMatrix (list_i &control_points)
void initializeControlPointVector (std::list< int > &control_points)
bool deviationsLarge (void)
void computeDeviations (void)
bool fewButKeep (void)
bool fewOmit (void)
void clearRadiusCurvatureLogFiles (void)
void clearArcLengthsLogFiles (void)
void clearUniformSampleLogFiles (void)
void clearSampleLogFiles (void)
void clearSParamLogFiles (void)
void clearControlLogFiles (void)
Constructor & Destructor Documentation
Contour::Contour (char *const str, int sec)
Contour::Contour (Contour const & rhs)
Member Function Documentation
Contour & Contour::operator= (Contour const & rhs)
References name.
int Contour::processContour (vec_d & my_path_intervals)
Fit splines to contour points in this contour.
Parameters:
$\rightarrow$ my_path_intervals Straight-line distance between successive spline samples.
Returns: Expected number of spline samples based on contour spline lengths and minimum and maximum sample intervals.
References calcSampleIntervals(), getName(), Control_Points::getNumSplines(), Controls::getOutputDir(), Controls::getPrintDetailedInfo(), getSection(), Controls::instance(), Parameter::print(), and Parameter::reserve().
bool Contour::isDegenerate (void) const
Determine if contour has too few samples to be a valid contour shape. Specifically, a contour with two or less points has zero circumscribing area and is an impossibly physiological shape.
Returns: True if contour is degenerate; false otherwise.
References Parameter::getNumSamplePoints().
void Contour::computeDeviationHistogram (Histogram & h) const
void Contour::computeIntervalHistogram (Histogram & h) const
void Contour::updateDeviations (Histogram & h) const
Update statistics of deviation of spline samples to linearly-interpolated raw contour points.
Parameters:
$\rightarrow$ h Instance of Histogram class for deviations.
References Parameter::getFirstDeviationConst(), Parameter::getOnePastLastDeviationConst(), and Histogram::update().
void Contour::calcSampleIntervals (vec_d & my_path_intervals)
Calculate straight-line distance between successive spline samples.
Parameters:
$\rightarrow$ my_path_intervals Inter-sample distances.
References Parameter::getFirstSplineSampleConst(), and Parameter::getOnePastLastSplineSampleConst().
Referenced by processContour().
void Contour::updateSampleIntervals (Histogram & h)
Calculate straight line distance between adjacent sample points, store, and update sample interval statistics.
Parameters:
$\rightarrow$ h Instance of Histogram class for sample intervals.
References Parameter::getFirstSplineSampleConst(), Parameter::getOnePastLastSplineSampleConst(), and Histogram::update().
void Contour::setSamplesToRaw (void)
Use the raw contour points as samples.
References Parameter::addDeviation(), Parameter::addSplineSample(), getName(), getSection(), and Controls::instance().
void Contour::removeDuplicates (void)
Compare sequential contour points and remove duplicate points.
References pointsAreIdentical().
void Contour::writeFilesAfter (void) const
Write diagnostic information to file.
References getName(), Control_Points::getNumSplines(), Controls::getOutputDir(), getSection(), Controls::instance(), Control_Points::print(), Parameter::print(), and printSplineSamplesHere().
void Contour::printPtsFiles (char const * myname) const
Write x and y values of spline samples to file in pts format.
Parameters:
$\leftarrow$ myname Contour name.
References Parameter::getFirstSplineSampleConst(), Parameter::getNumSamplePoints(), Parameter::getOnePastLastSplineSampleConst(), Controls::getOutputDir(), Controls::getOutputScaleFactor(), getSection(), Controls::getSectionThickness(), and Controls::instance().
void Contour::printRawPtsFiles (char const * myname) const
Write input contour points to file in pts format.
Parameters:
$\leftarrow$ myname Contour name.
References Controls::getOutputDir(), Controls::getOutputScaleFactor(), Controls::getSectionThickness(), and Controls::instance().
void Contour::printScripts (void) const
Write grace scripts for visualizing contours and spline samples.
References getName(), Controls::getOutputDir(), getSection(), and Controls::instance().
void Contour::printSimpleScripts (void) const
Write grace scripts for visualizing contours and spline samples.
References getName(), Controls::getOutputDir(), getSection(), and Controls::instance().
void Contour::printRawPoints (char const *const filename) const
Write input contour points to file.
Parameters:
$\leftarrow$ filename Output file name.
void Contour::printSplineSamplesHere (char const *const filename, const int & num_splines, double path_parameter_value) const
Write spline sample point evaluated at given parameter value.
Parameters:
$\leftarrow$ filename Output file name.
$\leftarrow$ num_splines Number of splines in contour.
$\leftarrow$ path_parameter_value Path parameter value of interest. Value must be between 0.0 and 1.0, inclusive.
References Parameter::getNumSamples(), Point::getX(), and Point::getY().
Referenced by writeFilesAfter().
void Contour::duplicateControlPoints (list_i & control_points) const
Duplicate control points of splines to reduce deviation between spline samples and linearly-interpolated raw contour points.
Parameters:
$\rightarrow$ control_points Indices of raw contour points used as control points for splines.
References Parameter::getRawPointsToDuplicate().
void Contour::printIdentity (void) [inline]
void Contour::addRawPoint (Point p) [inline]
int Contour::getNumSamplePoints (void) const [inline]
References Parameter::getNumSamplePoints().
int Contour::getNumRawPoints (void) const [inline]
Referenced by fewButKeep(), and fewOmit().
bool Contour::pointsAreIdentical (Point const & lhs, Point const & rhs) const [inline]
References Point::getX(), and Point::getY().
Referenced by removeDuplicates().
char const* Contour::getName (void) const [inline]
Referenced by clearArcLengthsLogFiles(), clearControlLogFiles(), clearRadiusCurvatureLogFiles(), clearSampleLogFiles(), clearSParamLogFiles(), clearUniformSampleLogFiles(), fewButKeep(), fewOmit(), printScripts(), printSimpleScripts(), processContour(), setSamplesToRaw(), and writeFilesAfter().
c_d_iterator Contour::firstDeviation (void) [inline]
References Parameter::getFirstDeviationConst().
c_d_iterator Contour::onePastLastDeviation (void) [inline]
References Parameter::getOnePastLastDeviationConst().
c_p_iterator Contour::getFirstRawPoint (void) [inline]
c_p_iterator Contour::getOnePastLastRawPoint (void) [inline]
int Contour::getSection (void) const [inline]
Referenced by clearArcLengthsLogFiles(), clearControlLogFiles(), clearRadiusCurvatureLogFiles(), clearSampleLogFiles(), clearSParamLogFiles(), clearUniformSampleLogFiles(), fewButKeep(), fewOmit(), printPtsFiles(), printScripts(), printSimpleScripts(), processContour(), setSamplesToRaw(), and writeFilesAfter().
void Contour::initializeControlPointMatrix (list_i & control_points) [inline]
Create matrix of control points describing all splines in contour.
Parameters:
$\leftarrow$ control_points Sequence of raw points to use as control_points.
References Control_Points::initialize().
void Contour::initializeControlPointVector (std::list< int > & control_points) [inline]
Create matrix of control points describing all splines in contour.
Parameters:
$\rightarrow$ control_points Sequence of raw points to use as control_points.
References Controls::getReturnInterpolatedRawPoints(), and Controls::instance().
bool Contour::deviationsLarge (void) [inline]
Check if any measured deviation of spline samples from linearly-connected raw contour points exceeds threshold.
Returns: True if deviation threshold is exceeded; false otherwise.
References Parameter::deviationsLarge().
void Contour::computeDeviations (void) [inline]
Compute deviation distance between raw points and splines.
References Parameter::computeDeviations().
bool Contour::fewButKeep (void) [inline]
Check if contour has too few raw points to spline but sufficent number to pass threshold criterion.
Returns: True if keep contour; false otherwise.
References getName(), getNumRawPoints(), Controls::getPtPerContourThreshold(), getSection(), and Controls::instance().
bool Contour::fewOmit (void) [inline]
Check if contour has too few raw points to spline and an insufficent number to pass threshold criterion.
Returns: True if omit contour; false otherwise.
References getName(), getNumRawPoints(), Controls::getPtPerContourThreshold(), getSection(), and Controls::instance().
void Contour::clearRadiusCurvatureLogFiles (void) [inline]
Initialize radius of curvature log file to empty.
References getName(), getSection(), and Controls::instance().
void Contour::clearArcLengthsLogFiles (void) [inline]
Initialize arc lengths log file to empty.
References getName(), getSection(), and Controls::instance().
void Contour::clearUniformSampleLogFiles (void) [inline]
Initialize log file to empty for spline samples at uniform path parameter.
References getName(), getSection(), and Controls::instance().
void Contour::clearSampleLogFiles (void) [inline]
Initialize log file to empty for spline samples.
References getName(), getSection(), and Controls::instance().
void Contour::clearSParamLogFiles (void) [inline]
Initialize path parameter log file to empty.
References getName(), getSection(), and Controls::instance().
void Contour::clearControlLogFiles (void) [inline]
Initialize log file to empty for indeces of control points.
References getName(), getSection(), and Controls::instance().
The documentation for this class was generated from the following files:
contour.h
contour.cc