Parameter Class Reference
#include <parameter.h>
Public Member Functions
void print (char const *const filename) const
void computeDeviations (const std::vector< Point > &raw_points)
void getRawPointsToDuplicate (const std::vector< Point > &raw_points, std::vector< int > &raw_points_to_duplicate) const
double calcMinDistPtLineSegment (const Point &spline_sample, const Point &contour_point_1, const Point &contour_point_3) const
void addDeviation (double d)
Parameter (void)
bool deviationsLarge (void)
void reserve (const int &target_num_samples)
Point const * getPoint (const int &sample_index) const
void clearAndReserveSamples (void)
void add (const double &path_parameter_value, const int &index_of_spline, const double &delta_s_to_lhs)
void set (double new_s, int new_spline_index, int sample_index, double s_disp, Point p)
int getNumSamplePoints (void) const
int getNumSamples (void) const
double getParameterValue (int sample_index) const
int getSplineIndex (int sample_index) const
double getLhsS (int sample_index) const
void addSplineSample (Point p)
c_d_iterator getFirstDeviationConst (void) const
c_d_iterator getOnePastLastDeviationConst (void) const
c_p_iterator getFirstSplineSampleConst (void) const
c_p_iterator getOnePastLastSplineSampleConst (void) const
Constructor & Destructor Documentation
Parameter::Parameter (void) [inline]
Member Function Documentation
void Parameter::print (char const *const filename) const
Write path parameter values, spline indices, and path parameter distances to left-hand side sample point to file.
Parameters:
$\leftarrow$ filename Output file name.
Referenced by Contour::processContour(), and Contour::writeFilesAfter().
void Parameter::computeDeviations (const std::vector< Point > & raw_points)
Calculate perpendicular distance between each spline samples and nearest linearly-interpolated raw contour points.
Parameters:
$\leftarrow$ raw_points All original points in contour.
References calcMinDistPtLineSegment().
Referenced by Contour::computeDeviations().
void Parameter::getRawPointsToDuplicate (const std::vector< Point > & raw_points, std::vector< int > & raw_points_to_duplicate) const
Determine which control points of splines to duplicate to reduce deviation between spline samples and linearly-interpolated raw contour points.
Parameters:
$\leftarrow$ raw_points All original points in contour.
$\rightarrow$ raw_points_to_duplicate Raw points that should be duplicated as control points.
References Controls::getDeviationThreshold(), and Controls::instance().
Referenced by Contour::duplicateControlPoints().
double Parameter::calcMinDistPtLineSegment (const Point & spline_sample, const Point & contour_point_1, const Point & contour_point_2) const
Calculate perpendicular distance from sample point to nearest raw contour point line segment.
Parameters:
$\leftarrow$ spline_sample Spline sample point of interest.
$\leftarrow$ contour_point_1 One end of line segment.
$\leftarrow$ contour_point_2 Other end of line segment.
Returns: Perpendicular distance from sample_point to line segment.
References Point::dot(), and Point::length().
Referenced by computeDeviations().
void Parameter::addDeviation (double d) [inline]
Referenced by Contour::setSamplesToRaw().
bool Parameter::deviationsLarge (void) [inline]
Determine if any deviation of sample points exceeds threshold.
References Controls::getDeviationThreshold(), and Controls::instance().
Referenced by Contour::deviationsLarge().
void Parameter::reserve (const int & target_num_samples) [inline]
Clear all class data and allocate memory.
Parameters:
$\leftarrow$ target_num_samples Amount of memory to reserve for future data.
Referenced by Contour::processContour().
Point const* Parameter::getPoint (const int & sample_index) const [inline]
Get sample point.
Parameters:
$\leftarrow$ sample_index Index of sample point of interest.
Returns: Sample point.
void Parameter::clearAndReserveSamples (void) [inline]
Clear samples and reallocate memory.
void Parameter::add (const double & path_parameter_value, const int & index_of_spline, const double & delta_s_to_lhs) [inline]
Add sample point.
Parameters:
$\leftarrow$ path_parameter_value Path parameter value of sample point for spline.
$\leftarrow$ index_of_spline Index of spline on which sample point lies.
$\leftarrow$ delta_s_to_lhs Path parameter distance to nearest sample point to the left.
void Parameter::set (double new_s, int new_spline_index, int sample_index, double s_disp, Point p) [inline]
Move spline sample point.
Parameters:
$\leftarrow$ new_s New path parameter value.
$\leftarrow$ new_spline_index Index of new spline on which point sits.
$\leftarrow$ sample_index Index of sample point being moved.
$\leftarrow$ s_disp Change in path parameter value from old value. Signed value.
$\leftarrow$ p New location of sample point.
References getNumSamples().
int Parameter::getNumSamplePoints (void) const [inline]
Referenced by Contour::getNumSamplePoints(), Contour::isDegenerate(), and Contour::printPtsFiles().
int Parameter::getNumSamples (void) const [inline]
Referenced by Contour::printSplineSamplesHere(), and set().
double Parameter::getParameterValue (int sample_index) const [inline]
int Parameter::getSplineIndex (int sample_index) const [inline]
double Parameter::getLhsS (int sample_index) const [inline]
void Parameter::addSplineSample (Point p) [inline]
Referenced by Contour::setSamplesToRaw().
c_d_iterator Parameter::getFirstDeviationConst (void) const [inline]
Referenced by Contour::firstDeviation(), and Contour::updateDeviations().
c_d_iterator Parameter::getOnePastLastDeviationConst (void) const [inline]
Referenced by Contour::onePastLastDeviation(), and Contour::updateDeviations().
c_p_iterator Parameter::getFirstSplineSampleConst (void) const [inline]
Referenced by Contour::calcSampleIntervals(), Contour::printPtsFiles(), and Contour::updateSampleIntervals().
c_p_iterator Parameter::getOnePastLastSplineSampleConst (void) const [inline]
Referenced by Contour::calcSampleIntervals(), Contour::printPtsFiles(), and Contour::updateSampleIntervals().
The documentation for this class was generated from the following files:
parameter.h
parameter.cc