Sim_Anneal Class Reference
#include <sim_anneal.h>
Public Member Functions
Sim_Anneal (void)
int getRandomSample (const int &num_samples)
bool moreMoves (const int &num_raw_points)
void printEnergy (char *const filename) const
void printTemperature (char *const filename) const
void printScript (const char *const energy_filename, const char *const temp_filename, const std::string &contour_name, const int &contour_section) const
void debug (const std::string &name, const int &section, const int &num_raw_points)
double getNormalRandom (void)
double getRandomPathParameterDisplacement (void)
void decreaseTemp (void)
bool isFrozen (void)
bool keepMove (double delta_energy)
void setScale (const int &num_samples)
void reserveDetailedInfo (void)
void recordDetailedInfo (const double &current_energy)
void recordSuccessfulMove (void)
void recordUnsuccessfulMove (void)
Constructor & Destructor Documentation
Sim_Anneal::Sim_Anneal (void)
Member Function Documentation
int Sim_Anneal::getRandomSample (const int & num_samples)
Pick random sample point from uniform distribution.
Parameters:
$\leftarrow$ num_samples Number of sample points in contour.
Returns: Index of sample point.
bool Sim_Anneal::moreMoves (const int & num_raw_points)
Determine if more sample moves should be made at current temperature.
Parameters:
$\leftarrow$ num_raw_points Number of raw points in contour.
Returns: True if move more sampe points; false otherwise;
References Controls::getMaxNumMoveAttempts(), Controls::getNumMovesPerIteration(), and Controls::instance().
void Sim_Anneal::printEnergy (char *const filename) const
Write energy history of simulated annealing to file.
Parameters:
$\leftarrow$ filename Output file name.
void Sim_Anneal::printTemperature (char *const filename) const
Write temperature history of simulated annealing to file.
Parameters:
$\leftarrow$ filename Output file name.
void Sim_Anneal::printScript (const char *const energy_filename, const char *const temp_filename, const std::string & contour_name, const int & contour_section) const
Write grace script for visualizing annealing energy and temperature.
Parameters:
$\leftarrow$ energy_filename Output file name for energy history.
$\leftarrow$ temp_filename Output file name for temperature history.
$\leftarrow$ contour_name Contour name.
$\leftarrow$ contour_section Contour section.
References Controls::getOutputDir(), and Controls::instance().
void Sim_Anneal::debug (const std::string & name, const int & section, const int & num_raw_points)
Print detailed information for debugging purposes.
Parameters:
$\leftarrow$ name Contour name.
$\leftarrow$ section Contour section.
$\leftarrow$ num_raw_points Number of raw points in contour.
References Controls::getMaxNumMoveAttempts(), Controls::getNumMovesPerIteration(), and Controls::instance().
double Sim_Anneal::getNormalRandom (void)
Get normally distributed random number with equal mean and standard deviation.
Returns: Random number.
References Controls::getMeanAmplitudeNoise(), and Controls::instance().
Referenced by getRandomPathParameterDisplacement().
double Sim_Anneal::getRandomPathParameterDisplacement (void) [inline]
Pick random path parameter displacement from normal distribution.
Returns: Path parameter displacement.
References getNormalRandom().
void Sim_Anneal::decreaseTemp (void) [inline]
Lower temperature and prepare for another set of sample moves.
References Controls::getBoltzman(), Controls::getTempScale(), and Controls::instance().
bool Sim_Anneal::isFrozen (void) [inline]
Determine if contour is `frozen` and simulated annealing is complete.
Returns: True if contour is frozen; false otherwise;
References Controls::instance().
bool Sim_Anneal::keepMove (double delta_energy) [inline]
Determine if sample point move that raised energy shoudl be kept.
Parameters:
$\leftarrow$ delta_energy Change in energy due to sample point move.
Returns: True if keep sample point move; false otherwise;
void Sim_Anneal::setScale (const int & num_samples) [inline]
void Sim_Anneal::reserveDetailedInfo (void) [inline]
void Sim_Anneal::recordDetailedInfo (const double & current_energy) [inline]
void Sim_Anneal::recordSuccessfulMove (void) [inline]
void Sim_Anneal::recordUnsuccessfulMove (void) [inline]
The documentation for this class was generated from the following files:
sim_anneal.h
sim_anneal.cc