Point Class Reference
#include <point.h>
Public Member Functions
Point (void)
Point (char const *str, double *const transform)
Point (double xval, double yval)
double getX (void) const
double getY (void) const
void setX (double i)
void setY (double i)
void print (char *const line) const
Point operator- (const Point &p) const
double dot (const Point &p) const
double distance_squared (const Point &p) const
double length (void) const
Point & operator*= (double a)
Constructor & Destructor Documentation
Point::Point (void)
Referenced by operator-().
Point::Point (char const * str, double *const transform)
Point::Point (double xval, double yval)
Member Function Documentation
double Point::getX (void) const [inline]
Referenced by Contour::pointsAreIdentical(), and Contour::printSplineSamplesHere().
double Point::getY (void) const [inline]
Referenced by Contour::pointsAreIdentical(), and Contour::printSplineSamplesHere().
void Point::setX (double i) [inline]
void Point::setY (double i) [inline]
void Point::print (char *const line) const [inline]
Point Point::operator- (const Point & p) const [inline]
References Point(), x, and y.
double Point::dot (const Point & p) const [inline]
References x, and y.
Referenced by Parameter::calcMinDistPtLineSegment().
double Point::distance_squared (const Point & p) const [inline]
References x, and y.
double Point::length (void) const [inline]
Referenced by Parameter::calcMinDistPtLineSegment().
Point& Point::operator*= (double a) [inline]
The documentation for this class was generated from the following files:
point.h
point.cc