Control_Points Class Reference
#include <control_points.h>
Public Member Functions
Control_Points (void)
int getNumSplines (void) const
void initialize (std::list< int > &control_points)
int getControlPointIndex (int i) const
void print (char *filename) const
Constructor & Destructor Documentation
Control_Points::Control_Points (void)
Member Function Documentation
int Control_Points::getNumSplines (void) const [inline]
Calculate number of splines defined by control points.
Returns: Number of splines.
Referenced by Contour::processContour(), and Contour::writeFilesAfter().
void Control_Points::initialize (std::list< int > & control_points) [inline]
Create matrix of control points describing all splines in contour.
Parameters:
$\leftarrow$ control_points Sequence of raw points to use as control_points.
Referenced by Contour::initializeControlPointMatrix().
int Control_Points::getControlPointIndex (int i) const [inline]
Get control point.
Parameters:
$\leftarrow$ i Index of control point of interest.
Returns: Index of raw contour point stored as control point.
void Control_Points::print (char * filename) const [inline]
Write control points (e.g. raw contour point indices) to file.
Parameters:
$\leftarrow$ filename Output file name.
Referenced by Contour::writeFilesAfter().
The documentation for this class was generated from the following files:
control_points.h
control_points.cc