reconstruct2contourtiler.cc File Reference
#include <stdlib.h>
#include <string>
#include <cmath>
#include `reconstruct2contourtiler.h`
Functions
int main (int argc, char *argv[])
bool distinguishable (double a, double b, double epsilon)
bool distinguishable (double a, double b)
Function Documentation
bool distinguishable (double a, double b)
Determine if two floating-point precision numbers are equivalent in value within MY_DOUBLE_EPSILON.
Parameters:
$\leftarrow$ a First number.
$\leftarrow$ b Second number.
Returns: 1 if Inputs are different; 0 otherwise.
References distinguishable(), and Controls::instance().
bool distinguishable (double a, double b, double epsilon)
Determine if two floating-point precision numbers are equivalent in value within epsilon.
Parameters:
$\leftarrow$ a First number.
$\leftarrow$ b Second number.
$\leftarrow$ epsilon The difference between the two input values must be greater than the fraction of the largest input value defined by epsilon.
Returns: 1 if Inputs are different; 0 otherwise.
Referenced by distinguishable().
int main (int argc, char * argv[])
References Container::clearOutputScripts(), Container::getContours(), Container::getNumContours(), Container::getNumFiles(), Container::getNumObjects(), Container::getNumRawPoints(), Controls::getPrintDetailedInfo(), Controls::instance(), Controls::parseCommandLine(), Container::printRawPoints(), Histogram::printStatistics(), Container::processContour(), Container::removeDuplicates(), and Container::writeOutputContours().