#!/usr/bin/perl -w

$min=0;
$max=689;
$obj="post";
$count=1;

for ($i=$min;$i<=$max;$i++) {
  $count=sprintf("%04d",$i);
  print "tifftopnm ./tif/$obj.$count.tif > ./pgm/$obj.pgm.$i\n";
  `tifftopnm ./tif/$obj.$count.tif > ./pgm/$obj.pgm.$i`;
}

