#!/bin/bash

reconstruct2contourtiler -i input \
-o output -I cube -I cyl -I grid -I domain1 \
--min_section=99 --max_section=99 \
--curvature_gain=1E2 --curvature_exponent=1 \
--proximity_gain=3E0 --proximity_exponent=1 \
--min_point_per_contour=0 \
--deviation_threshold=0.005
