VTrack Class Reference
#include <vtrack.h>
Public Member Functions
VTrack (void)
VTrack (VTrack const &)
VTrack & operator= (VTrack const &)
bool isGood (void)
void clear (void)
void print (void)
void printBad (void)
void addNewSepDis (double)
void addOrigP (vec_d const *const)
void addNewP (vec_d const *const)
void addOrigCP (double[3])
void addNewCP (double[3])
void addVertex (Vertex *)
void addNewVD (double)
void addNewTopN (double)
void addOrigSepDis (double)
void addOrigVD (double)
void addOrigTopN (double)
void premove (Vertex *)
void postmove (void)
double getNewSepDis (void)
double getNewVD (void)
double getNewTopN (void)
double getOrigSepDis (void)
double getOrigVD (void)
double getOrigTopN (void)
Vertex * getVertex (void)
Detailed Description
Definition at line 6 of file vtrack.h.
Constructor & Destructor Documentation
VTrack::VTrack (void)
Definition at line 14 of file vtrack.cc.
VTrack::VTrack (VTrack const &)
Definition at line 21 of file vtrack.cc.
References Vertex::getIndex(), and vv.
Member Function Documentation
VTrack & VTrack::operator= (VTrack const &)
Definition at line 31 of file vtrack.cc.
References Vertex::getIndex(), and vv.
bool VTrack::isGood (void)
Definition at line 100 of file vtrack.cc.
Referenced by postmove().
void VTrack::clear (void)
Definition at line 175 of file vtrack.cc.
Referenced by premove().
void VTrack::print (void)
Definition at line 63 of file vtrack.cc.
Referenced by postmove().
void VTrack::printBad (void)
Definition at line 38 of file vtrack.cc.
Referenced by postmove().
void VTrack::addNewSepDis (double)
Definition at line 115 of file vtrack.cc.
Referenced by postmove().
void VTrack::addOrigP (vec_d const * const)
Definition at line 194 of file vtrack.cc.
Referenced by premove().
void VTrack::addNewP (vec_d const * const)
Definition at line 222 of file vtrack.cc.
Referenced by postmove().
void VTrack::addOrigCP (double[3])
Definition at line 229 of file vtrack.cc.
Referenced by premove().
void VTrack::addNewCP (double[3])
Definition at line 250 of file vtrack.cc.
Referenced by postmove().
void VTrack::addVertex (Vertex *)
Definition at line 95 of file vtrack.cc.
Referenced by premove().
void VTrack::addNewVD (double)
Definition at line 125 of file vtrack.cc.
Referenced by postmove().
void VTrack::addNewTopN (double)
Definition at line 135 of file vtrack.cc.
Referenced by postmove().
void VTrack::addOrigSepDis (double)
Definition at line 145 of file vtrack.cc.
Referenced by premove().
void VTrack::addOrigVD (double)
Definition at line 155 of file vtrack.cc.
Referenced by premove().
void VTrack::addOrigTopN (double)
Definition at line 165 of file vtrack.cc.
Referenced by premove().
void VTrack::premove (Vertex *)
Definition at line 257 of file vtrack.cc.
References addOrigCP(), addOrigP(), addOrigSepDis(), addOrigTopN(), addOrigVD(), addVertex(), clear(), Virtual_Disp::findTopN(), Container::getNearPtOnFaceToVertex(), Vertex::getSqSepDist(), Container::instance(), Virtual_Disp::instance(), and Vertex_Schedule::instance().
Referenced by main().
void VTrack::postmove (void)
Definition at line 276 of file vtrack.cc.
References addNewCP(), addNewP(), addNewSepDis(), addNewTopN(), addNewVD(), Virtual_Disp::findTopN(), Container::getNearPtOnFaceToVertex(), Container::instance(), Virtual_Disp::instance(), Vertex_Schedule::instance(), isGood(), print(), and printBad().
Referenced by main().
double VTrack::getNewSepDis (void)
Definition at line 120 of file vtrack.cc.
double VTrack::getNewVD (void)
Definition at line 130 of file vtrack.cc.
double VTrack::getNewTopN (void)
Definition at line 140 of file vtrack.cc.
double VTrack::getOrigSepDis (void)
Definition at line 150 of file vtrack.cc.
double VTrack::getOrigVD (void)
Definition at line 160 of file vtrack.cc.
double VTrack::getOrigTopN (void)
Definition at line 170 of file vtrack.cc.
Vertex * VTrack::getVertex (void)
Definition at line 90 of file vtrack.cc.
The documentation for this class was generated from the following files:
vtrack.h
vtrack.cc